
package com.Juego;

import java.applet.AudioClip;

/**
 *
 * @author Daniuws
 */
public class menu extends javax.swing.JFrame {

        private AudioClip sound;

    /**
     * Creates new form menu
     */
    public menu() {
        initComponents();
        playSound();
    }
    
    private void playSound() {
        sound = java.applet.Applet.newAudioClip(getClass().getResource("../audios/audioMusic.wav"));
        sound.play();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        prinMenuAcceder = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        menuIngresar = new javax.swing.JButton();
        menubotPrinCrearAccount = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        botLogros = new javax.swing.JButton();
        botDudas = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1000, 550));

        jPanel1.setBackground(new java.awt.Color(255, 213, 129));
        jPanel1.setMaximumSize(new java.awt.Dimension(1000, 550));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        prinMenuAcceder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/menuPrinCrearAccount.png"))); // NOI18N
        jPanel1.add(prinMenuAcceder, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 430, 239, 74));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/menuPrinAcceder.png"))); // NOI18N
        jLabel2.setPreferredSize(new java.awt.Dimension(298, 101));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 310, -1, -1));

        menuIngresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/menuPrintbotJUgar.png"))); // NOI18N
        menuIngresar.setBorder(null);
        menuIngresar.setContentAreaFilled(false);
        menuIngresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuIngresarActionPerformed(evt);
            }
        });
        jPanel1.add(menuIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 320, 242, 83));

        menubotPrinCrearAccount.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/menuBotPrinCrearAccount).png"))); // NOI18N
        menubotPrinCrearAccount.setBorder(null);
        menubotPrinCrearAccount.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menubotPrinCrearAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menubotPrinCrearAccountActionPerformed(evt);
            }
        });
        jPanel1.add(menubotPrinCrearAccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 440, 259, 55));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/RECUERDAME (9).png"))); // NOI18N
        jLabel3.setMaximumSize(new java.awt.Dimension(95, 168));
        jLabel3.setMinimumSize(new java.awt.Dimension(95, 168));
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 350, 94, 166));

        botLogros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/RECUERDAME (13).png"))); // NOI18N
        botLogros.setBorder(null);
        botLogros.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botLogros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botLogrosActionPerformed(evt);
            }
        });
        jPanel1.add(botLogros, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 340, 190, 100));

        botDudas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/RECUERDAME (14).png"))); // NOI18N
        botDudas.setBorder(null);
        botDudas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botDudas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botDudasActionPerformed(evt);
            }
        });
        jPanel1.add(botDudas, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 440, 191, 100));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/logo1Menu.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 100));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/RECUERDAME (7).png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, 695, 195));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/RECUERDAME (8).png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 192, 183));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/RECUERDAME (5).png"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 90, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menubotPrinCrearAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menubotPrinCrearAccountActionPerformed
       com.Login.Login newAccount = new com.Login.Login();
        newAccount.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menubotPrinCrearAccountActionPerformed

    private void menuIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuIngresarActionPerformed
        com.ingreso.ingresar newPlay = new com.ingreso.ingresar();
        newPlay.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menuIngresarActionPerformed

    private void botLogrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botLogrosActionPerformed
        com.Logros.Logros newLogros = new com.Logros.Logros();
        newLogros.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_botLogrosActionPerformed

    private void botDudasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botDudasActionPerformed
        com.Dudas.Dudas newDudas = new com.Dudas.Dudas();
        newDudas.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_botDudasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botDudas;
    private javax.swing.JButton botLogros;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton menuIngresar;
    private javax.swing.JButton menubotPrinCrearAccount;
    private javax.swing.JLabel prinMenuAcceder;
    // End of variables declaration//GEN-END:variables
}
