package com.Juego;

import java.applet.AudioClip;



/**
 *
 * @author Daniusw, 
 */
public class menu_02 extends javax.swing.JFrame {

     private AudioClip sound;
     
    public menu_02() {
        initComponents();
        playSound();
    }
    
    private void playSound() {
        sound = java.applet.Applet.newAudioClip(getClass().getResource("../audios/MenuMusica.wav"));
        sound.play();
    }
    private void stopSound() {
        if (sound != null) {
        sound.stop();
        }
    } 
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        botCrearAccount = new javax.swing.JButton();
        botSoporte = new javax.swing.JButton();
        BotLogros = new javax.swing.JButton();
        BotIngresar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 113));
        jPanel1.setMaximumSize(new java.awt.Dimension(1000, 550));
        jPanel1.setMinimumSize(new java.awt.Dimension(1000, 550));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botCrearAccount.setBackground(new java.awt.Color(200, 81, 3));
        botCrearAccount.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 18)); // NOI18N
        botCrearAccount.setForeground(new java.awt.Color(255, 255, 255));
        botCrearAccount.setText("CREAR CUENTA");
        botCrearAccount.setBorder(null);
        botCrearAccount.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botCrearAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botCrearAccountActionPerformed(evt);
            }
        });
        jPanel1.add(botCrearAccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 400, 180, 50));

        botSoporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/RECUERDAME (14).png"))); // NOI18N
        botSoporte.setBorder(null);
        botSoporte.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botSoporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botSoporteActionPerformed(evt);
            }
        });
        jPanel1.add(botSoporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 450, 190, 90));

        BotLogros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/RECUERDAME (13).png"))); // NOI18N
        BotLogros.setBorder(null);
        BotLogros.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotLogros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotLogrosActionPerformed(evt);
            }
        });
        jPanel1.add(BotLogros, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 350, 190, 90));

        BotIngresar.setBackground(new java.awt.Color(200, 81, 3));
        BotIngresar.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 24)); // NOI18N
        BotIngresar.setForeground(new java.awt.Color(255, 255, 255));
        BotIngresar.setText("JUGAR");
        BotIngresar.setBorder(null);
        BotIngresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotIngresarActionPerformed(evt);
            }
        });
        jPanel1.add(BotIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 310, 130, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gifs/menuNew_09.gif"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 920, 450));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botCrearAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botCrearAccountActionPerformed
        stopSound();
        com.Login.Login newAccount = new com.Login.Login();
        newAccount.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_botCrearAccountActionPerformed

    private void BotIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotIngresarActionPerformed
        stopSound();
        com.ingreso.ingresar newPlay = new com.ingreso.ingresar();
        newPlay.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BotIngresarActionPerformed

    private void botSoporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botSoporteActionPerformed
        stopSound();
        com.Dudas.Dudas newDudas = new com.Dudas.Dudas();
        newDudas.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_botSoporteActionPerformed

    private void BotLogrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotLogrosActionPerformed
        stopSound();
        com.Logros.Logros newLogros = new com.Logros.Logros();
        newLogros.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BotLogrosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu_02.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu_02.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu_02.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu_02.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu_02().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotIngresar;
    private javax.swing.JButton BotLogros;
    private javax.swing.JButton botCrearAccount;
    private javax.swing.JButton botSoporte;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
