/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.Juego.jFramesBasicosDeTodo;

/**
 *
 * @author user
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        botPrinJugar = new javax.swing.JButton();
        botPrinEstadis = new javax.swing.JButton();
        botPrinDudas = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        botPrinCrearAccount = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1000, 600));

        jPanel1.setBackground(new java.awt.Color(255, 213, 129));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setMaximumSize(new java.awt.Dimension(1000, 550));
        jPanel1.setMinimumSize(new java.awt.Dimension(1000, 550));
        jPanel1.setPreferredSize(new java.awt.Dimension(1000, 550));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/RECUERDAME (5).png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 100, 110, 200));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/RECUERDAME (8).png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 198, 180));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/RECUERDAME (7).png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, -1, 200));

        jLabel3.setForeground(new java.awt.Color(255, 213, 129));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/RECUERDAME (9).png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 370, 100, 160));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/RECUERDAME (11).png"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, 300, 100));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/logo1Menu.png"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        botPrinJugar.setBackground(new java.awt.Color(255, 213, 129));
        botPrinJugar.setForeground(new java.awt.Color(255, 213, 129));
        botPrinJugar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/RECUERDAME (12).png"))); // NOI18N
        botPrinJugar.setToolTipText("");
        botPrinJugar.setBorderPainted(false);
        botPrinJugar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botPrinJugar.setDefaultCapable(false);
        botPrinJugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botPrinJugarActionPerformed(evt);
            }
        });
        jPanel1.add(botPrinJugar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 340, 240, 80));

        botPrinEstadis.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/RECUERDAME (13).png"))); // NOI18N
        botPrinEstadis.setBorderPainted(false);
        botPrinEstadis.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botPrinEstadis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botPrinEstadisActionPerformed(evt);
            }
        });
        jPanel1.add(botPrinEstadis, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 340, 190, 100));

        botPrinDudas.setBackground(new java.awt.Color(255, 213, 129));
        botPrinDudas.setForeground(new java.awt.Color(255, 213, 129));
        botPrinDudas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/RECUERDAME (14).png"))); // NOI18N
        botPrinDudas.setBorderPainted(false);
        botPrinDudas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(botPrinDudas, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 440, 200, 100));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/menuPrinCrearAccount.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 450, 240, 70));

        botPrinCrearAccount.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/menuBotPrinCrearAccount).png"))); // NOI18N
        botPrinCrearAccount.setBorder(null);
        botPrinCrearAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botPrinCrearAccountActionPerformed(evt);
            }
        });
        jPanel1.add(botPrinCrearAccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 460, 250, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botPrinJugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botPrinJugarActionPerformed
        
    }//GEN-LAST:event_botPrinJugarActionPerformed

    private void botPrinEstadisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botPrinEstadisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botPrinEstadisActionPerformed

    private void botPrinCrearAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botPrinCrearAccountActionPerformed
        pruebaVent newframe = new pruebaVent();
        newframe.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_botPrinCrearAccountActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botPrinCrearAccount;
    private javax.swing.JButton botPrinDudas;
    private javax.swing.JButton botPrinEstadis;
    private javax.swing.JButton botPrinJugar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
